# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CodeHistoryViewer.ui'
#
# Created: Sat Sep 29 10:22:24 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CodeHistoryViewer(object):
    def setupUi(self, CodeHistoryViewer):
        CodeHistoryViewer.setObjectName(_fromUtf8("CodeHistoryViewer"))
        CodeHistoryViewer.resize(1130, 658)
        self.verticalLayout_9 = QtGui.QVBoxLayout(CodeHistoryViewer)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.widget_2 = QtGui.QWidget(CodeHistoryViewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout = QtGui.QGridLayout(self.widget_2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter_2 = QtGui.QSplitter(self.widget_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setOpaqueResize(True)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.widget = QtGui.QWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.authorSearchEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorSearchEdit.sizePolicy().hasHeightForWidth())
        self.authorSearchEdit.setSizePolicy(sizePolicy)
        self.authorSearchEdit.setObjectName(_fromUtf8("authorSearchEdit"))
        self.horizontalLayout_5.addWidget(self.authorSearchEdit)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.reviewerSearchEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reviewerSearchEdit.sizePolicy().hasHeightForWidth())
        self.reviewerSearchEdit.setSizePolicy(sizePolicy)
        self.reviewerSearchEdit.setObjectName(_fromUtf8("reviewerSearchEdit"))
        self.horizontalLayout_5.addWidget(self.reviewerSearchEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_6.addWidget(self.label_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.pathSearchEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathSearchEdit.sizePolicy().hasHeightForWidth())
        self.pathSearchEdit.setSizePolicy(sizePolicy)
        self.pathSearchEdit.setObjectName(_fromUtf8("pathSearchEdit"))
        self.verticalLayout_5.addWidget(self.pathSearchEdit)
        self.logSearchEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logSearchEdit.sizePolicy().hasHeightForWidth())
        self.logSearchEdit.setSizePolicy(sizePolicy)
        self.logSearchEdit.setObjectName(_fromUtf8("logSearchEdit"))
        self.verticalLayout_5.addWidget(self.logSearchEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_2.setObjectName(_fromUtf8("dateTimeEdit_2"))
        self.verticalLayout_3.addWidget(self.dateTimeEdit_2)
        self.dateTimeEdit_3 = QtGui.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_3.setObjectName(_fromUtf8("dateTimeEdit_3"))
        self.verticalLayout_3.addWidget(self.dateTimeEdit_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.spinBox = QtGui.QSpinBox(self.groupBox)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.verticalLayout.addWidget(self.spinBox)
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.verticalLayout.addWidget(self.spinBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.searchBtn = QtGui.QPushButton(self.widget)
        self.searchBtn.setObjectName(_fromUtf8("searchBtn"))
        self.horizontalLayout_10.addWidget(self.searchBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.revisions = QtGui.QTableView(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.revisions.sizePolicy().hasHeightForWidth())
        self.revisions.setSizePolicy(sizePolicy)
        self.revisions.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.revisions.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.revisions.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.revisions.setShowGrid(False)
        self.revisions.setSortingEnabled(True)
        self.revisions.setCornerButtonEnabled(False)
        self.revisions.setObjectName(_fromUtf8("revisions"))
        self.revisions.horizontalHeader().setStretchLastSection(True)
        self.revisions.verticalHeader().setVisible(False)
        self.verticalLayout_8.addWidget(self.revisions)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.messages = QtGui.QTextEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messages.sizePolicy().hasHeightForWidth())
        self.messages.setSizePolicy(sizePolicy)
        self.messages.setMinimumSize(QtCore.QSize(0, 0))
        self.messages.setReadOnly(True)
        self.messages.setObjectName(_fromUtf8("messages"))
        self.changedFiles = QtGui.QTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changedFiles.sizePolicy().hasHeightForWidth())
        self.changedFiles.setSizePolicy(sizePolicy)
        self.changedFiles.setMinimumSize(QtCore.QSize(0, 0))
        self.changedFiles.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.changedFiles.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.changedFiles.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.changedFiles.setShowGrid(False)
        self.changedFiles.setCornerButtonEnabled(False)
        self.changedFiles.setObjectName(_fromUtf8("changedFiles"))
        self.changedFiles.horizontalHeader().setStretchLastSection(True)
        self.changedFiles.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.closeBtn = QtGui.QPushButton(CodeHistoryViewer)
        self.closeBtn.setAutoDefault(False)
        self.closeBtn.setObjectName(_fromUtf8("closeBtn"))
        self.horizontalLayout.addWidget(self.closeBtn)
        self.verticalLayout_9.addLayout(self.horizontalLayout)

        self.retranslateUi(CodeHistoryViewer)
        QtCore.QObject.connect(self.closeBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), CodeHistoryViewer.reject)
        QtCore.QMetaObject.connectSlotsByName(CodeHistoryViewer)
        CodeHistoryViewer.setTabOrder(self.revisions, self.messages)
        CodeHistoryViewer.setTabOrder(self.messages, self.changedFiles)

    def retranslateUi(self, CodeHistoryViewer):
        CodeHistoryViewer.setWindowTitle(QtGui.QApplication.translate("CodeHistoryViewer", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CodeHistoryViewer", "Author:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CodeHistoryViewer", "Reviewer:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CodeHistoryViewer", "Changed Path: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CodeHistoryViewer", "Log Message:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CodeHistoryViewer", "From Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CodeHistoryViewer", "To Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CodeHistoryViewer", "From Revision", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("CodeHistoryViewer", "To Revision", None, QtGui.QApplication.UnicodeUTF8))
        self.searchBtn.setText(QtGui.QApplication.translate("CodeHistoryViewer", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.closeBtn.setText(QtGui.QApplication.translate("CodeHistoryViewer", "Close", None, QtGui.QApplication.UnicodeUTF8))

